### ISSUE TITLE
Set in test only mode

### ISSUE THREAD

**Issue by LanceVGoss** [jprsd/Android-PS3-Manager#1]
Can install Apk as it's set in test only mode however looking at this seems to have potential being new compared to the old apps that do this none of which work well now I hope Rtm and memory viewing would be a nice additional add something none have.

**Comment by jprsd** [comment]
Thanks for letting me know about this issue. I just updated the build configuration of the apk from debug to release. You should be able to install it now. Let me know if you run into any other problems.
